services:
  vectra.api:
    image: ${DOCKER_REGISTRY-}vectraapi
    build:
      context: ..
      dockerfile: backend/src/Vectra.API/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: vectra-postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C --no-locale
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  dataprotection-keys:  