@Vectra.API_HostAddress = http://localhost:8080
@Vectra.API_HostAddressHttps = https://localhost:8081

### Get Weather Forecast
GET {{Vectra.API_HostAddress}}/weatherforecast/
Accept: application/json

### Get Weather Forecast (HTTPS)
GET {{Vectra.API_HostAddressHttps}}/weatherforecast/
Accept: application/json